/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TraseeRouteImport } from './routes/trasee'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PersonalitatiRouteImport } from './routes/personalitati'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as IstoriaPloiestiuluiRouteImport } from './routes/istoria-ploiestiului'
import { Route as HartiRouteImport } from './routes/harti'
import { Route as DespreProiectRouteImport } from './routes/despre-proiect'
import { Route as CookiePolicyRouteImport } from './routes/cookie-policy'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ArhivaRouteImport } from './routes/arhiva'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BSlugRouteImport } from './routes/b.$slug'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'
import { Route as DotlovableOauthConsentRouteImport } from './routes/[.]lovable.oauth.consent'
import { Route as AuthenticatedAdminBuildingsNewRouteImport } from './routes/_authenticated/admin_.buildings.new'
import { Route as AuthenticatedAdminBuildingsIdEditRouteImport } from './routes/_authenticated/admin_.buildings.$id.edit'

const TraseeRoute = TraseeRouteImport.update({
  id: '/trasee',
  path: '/trasee',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PersonalitatiRoute = PersonalitatiRouteImport.update({
  id: '/personalitati',
  path: '/personalitati',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const IstoriaPloiestiuluiRoute = IstoriaPloiestiuluiRouteImport.update({
  id: '/istoria-ploiestiului',
  path: '/istoria-ploiestiului',
  getParentRoute: () => rootRouteImport,
} as any)
const HartiRoute = HartiRouteImport.update({
  id: '/harti',
  path: '/harti',
  getParentRoute: () => rootRouteImport,
} as any)
const DespreProiectRoute = DespreProiectRouteImport.update({
  id: '/despre-proiect',
  path: '/despre-proiect',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiePolicyRoute = CookiePolicyRouteImport.update({
  id: '/cookie-policy',
  path: '/cookie-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ArhivaRoute = ArhivaRouteImport.update({
  id: '/arhiva',
  path: '/arhiva',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BSlugRoute = BSlugRouteImport.update({
  id: '/b/$slug',
  path: '/b/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)
const DotlovableOauthConsentRoute = DotlovableOauthConsentRouteImport.update({
  id: '/.lovable/oauth/consent',
  path: '/.lovable/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminBuildingsNewRoute =
  AuthenticatedAdminBuildingsNewRouteImport.update({
    id: '/admin_/buildings/new',
    path: '/admin/buildings/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminBuildingsIdEditRoute =
  AuthenticatedAdminBuildingsIdEditRouteImport.update({
    id: '/admin_/buildings/$id/edit',
    path: '/admin/buildings/$id/edit',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/arhiva': typeof ArhivaRoute
  '/auth': typeof AuthRoute
  '/cookie-policy': typeof CookiePolicyRoute
  '/despre-proiect': typeof DespreProiectRoute
  '/harti': typeof HartiRoute
  '/istoria-ploiestiului': typeof IstoriaPloiestiuluiRoute
  '/mcp': typeof McpRoute
  '/personalitati': typeof PersonalitatiRoute
  '/reset-password': typeof ResetPasswordRoute
  '/trasee': typeof TraseeRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/b/$slug': typeof BSlugRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/admin/buildings/new': typeof AuthenticatedAdminBuildingsNewRoute
  '/admin/buildings/$id/edit': typeof AuthenticatedAdminBuildingsIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/arhiva': typeof ArhivaRoute
  '/auth': typeof AuthRoute
  '/cookie-policy': typeof CookiePolicyRoute
  '/despre-proiect': typeof DespreProiectRoute
  '/harti': typeof HartiRoute
  '/istoria-ploiestiului': typeof IstoriaPloiestiuluiRoute
  '/mcp': typeof McpRoute
  '/personalitati': typeof PersonalitatiRoute
  '/reset-password': typeof ResetPasswordRoute
  '/trasee': typeof TraseeRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/b/$slug': typeof BSlugRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/admin/buildings/new': typeof AuthenticatedAdminBuildingsNewRoute
  '/admin/buildings/$id/edit': typeof AuthenticatedAdminBuildingsIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/arhiva': typeof ArhivaRoute
  '/auth': typeof AuthRoute
  '/cookie-policy': typeof CookiePolicyRoute
  '/despre-proiect': typeof DespreProiectRoute
  '/harti': typeof HartiRoute
  '/istoria-ploiestiului': typeof IstoriaPloiestiuluiRoute
  '/mcp': typeof McpRoute
  '/personalitati': typeof PersonalitatiRoute
  '/reset-password': typeof ResetPasswordRoute
  '/trasee': typeof TraseeRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/b/$slug': typeof BSlugRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/_authenticated/admin_/buildings/new': typeof AuthenticatedAdminBuildingsNewRoute
  '/_authenticated/admin_/buildings/$id/edit': typeof AuthenticatedAdminBuildingsIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/arhiva'
    | '/auth'
    | '/cookie-policy'
    | '/despre-proiect'
    | '/harti'
    | '/istoria-ploiestiului'
    | '/mcp'
    | '/personalitati'
    | '/reset-password'
    | '/trasee'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/admin'
    | '/b/$slug'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/admin/buildings/new'
    | '/admin/buildings/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/arhiva'
    | '/auth'
    | '/cookie-policy'
    | '/despre-proiect'
    | '/harti'
    | '/istoria-ploiestiului'
    | '/mcp'
    | '/personalitati'
    | '/reset-password'
    | '/trasee'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/admin'
    | '/b/$slug'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/admin/buildings/new'
    | '/admin/buildings/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/arhiva'
    | '/auth'
    | '/cookie-policy'
    | '/despre-proiect'
    | '/harti'
    | '/istoria-ploiestiului'
    | '/mcp'
    | '/personalitati'
    | '/reset-password'
    | '/trasee'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/_authenticated/admin'
    | '/b/$slug'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/_authenticated/admin_/buildings/new'
    | '/_authenticated/admin_/buildings/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  ArhivaRoute: typeof ArhivaRoute
  AuthRoute: typeof AuthRoute
  CookiePolicyRoute: typeof CookiePolicyRoute
  DespreProiectRoute: typeof DespreProiectRoute
  HartiRoute: typeof HartiRoute
  IstoriaPloiestiuluiRoute: typeof IstoriaPloiestiuluiRoute
  McpRoute: typeof McpRoute
  PersonalitatiRoute: typeof PersonalitatiRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  TraseeRoute: typeof TraseeRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  BSlugRoute: typeof BSlugRoute
  DotlovableOauthConsentRoute: typeof DotlovableOauthConsentRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/trasee': {
      id: '/trasee'
      path: '/trasee'
      fullPath: '/trasee'
      preLoaderRoute: typeof TraseeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/personalitati': {
      id: '/personalitati'
      path: '/personalitati'
      fullPath: '/personalitati'
      preLoaderRoute: typeof PersonalitatiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/istoria-ploiestiului': {
      id: '/istoria-ploiestiului'
      path: '/istoria-ploiestiului'
      fullPath: '/istoria-ploiestiului'
      preLoaderRoute: typeof IstoriaPloiestiuluiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/harti': {
      id: '/harti'
      path: '/harti'
      fullPath: '/harti'
      preLoaderRoute: typeof HartiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/despre-proiect': {
      id: '/despre-proiect'
      path: '/despre-proiect'
      fullPath: '/despre-proiect'
      preLoaderRoute: typeof DespreProiectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookie-policy': {
      id: '/cookie-policy'
      path: '/cookie-policy'
      fullPath: '/cookie-policy'
      preLoaderRoute: typeof CookiePolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/arhiva': {
      id: '/arhiva'
      path: '/arhiva'
      fullPath: '/arhiva'
      preLoaderRoute: typeof ArhivaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/b/$slug': {
      id: '/b/$slug'
      path: '/b/$slug'
      fullPath: '/b/$slug'
      preLoaderRoute: typeof BSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.lovable/oauth/consent': {
      id: '/.lovable/oauth/consent'
      path: '/.lovable/oauth/consent'
      fullPath: '/.lovable/oauth/consent'
      preLoaderRoute: typeof DotlovableOauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin_/buildings/new': {
      id: '/_authenticated/admin_/buildings/new'
      path: '/admin/buildings/new'
      fullPath: '/admin/buildings/new'
      preLoaderRoute: typeof AuthenticatedAdminBuildingsNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin_/buildings/$id/edit': {
      id: '/_authenticated/admin_/buildings/$id/edit'
      path: '/admin/buildings/$id/edit'
      fullPath: '/admin/buildings/$id/edit'
      preLoaderRoute: typeof AuthenticatedAdminBuildingsIdEditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedAdminBuildingsNewRoute: typeof AuthenticatedAdminBuildingsNewRoute
  AuthenticatedAdminBuildingsIdEditRoute: typeof AuthenticatedAdminBuildingsIdEditRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedAdminBuildingsNewRoute: AuthenticatedAdminBuildingsNewRoute,
  AuthenticatedAdminBuildingsIdEditRoute:
    AuthenticatedAdminBuildingsIdEditRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  ArhivaRoute: ArhivaRoute,
  AuthRoute: AuthRoute,
  CookiePolicyRoute: CookiePolicyRoute,
  DespreProiectRoute: DespreProiectRoute,
  HartiRoute: HartiRoute,
  IstoriaPloiestiuluiRoute: IstoriaPloiestiuluiRoute,
  McpRoute: McpRoute,
  PersonalitatiRoute: PersonalitatiRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  TraseeRoute: TraseeRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  BSlugRoute: BSlugRoute,
  DotlovableOauthConsentRoute: DotlovableOauthConsentRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'

import type { startInstance } from './start.ts'

declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
